Create map
Thermalight/ProjectCgroup1 pull request #16
Opened 2022-11-28 17:59 UTC by MustacheAltun

2022-11-28 18:17 UTC, bleutjejr requested changes
Wanneer je op het dashboard bent en je herlaadt de pagina, dan wordt de pagina niet meer gevonden.

2022-11-28 18:19 UTC, bleutjejr commented
De kaart werkt nog niet samen met de status van een event. Deze wordt namelijk in de kaart nog niet geüpdated.

2022-11-28 18:29 UTC, MustacheAltun commented
> Wanneer je op het dashboard bent en je herlaadt de pagina, dan wordt de pagina niet meer gevonden.

dit heeft niet met de map te maken, maar met de service worker denk ik. of misschien een ander file. In ieder geval is dit een merge voor de map en niet service worker fixen of dergelijks.

2022-11-28 19:10 UTC, bleutjejr commented
Ik begrijp dat dit probleem niet zo zeer te maken heeft met de map, maar het probleem ontstaat wel in deze pull request. Voor dat dit dus gemerged kan worden, moet eerst dit probleem verholpen zijn.
Van: ***@***.***>
Verzonden: maandag 28 november 2022 19:30
Aan: ***@***.***>
CC: Leon ***@***.***>; ***@***.***>
Onderwerp: Re: [Thermalight/ProjectCgroup1] Create map (PR #16)


Wanneer je op het dashboard bent en je herlaadt de pagina, dan wordt de pagina niet meer gevonden.

dit heeft niet met de map te maken, maar met de service worker denk ik. of misschien een ander file. In ieder geval is dit een merge voor de map en niet service worker fixen of dergelijks.

—
Reply to this email directly, view it on GitHub<https://github.com/Thermalight/ProjectCgroup1/pull/16#issuecomment-1329554636>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AVYHCBNA2WDT3AX43SQ3VXLWKT22NANCNFSM6AAAAAASNTL33E>.
You are receiving this because you commented.Message ID: ***@***.***>

2022-11-28 19:15 UTC, bleutjejr commented
> De kaart werkt nog niet samen met de status van een event. Deze wordt namelijk in de kaart nog niet geüpdated.

Kan je iets duidelijker zijn of aantonen? omdat dit wel bij mij werkt. 

> Laat maar, dat doet-ie inderdaad wel. Je moet eerst ergens anders op klikken en opnieuw het event selecteren. Dan zie je de aangepaste status.

2022-11-29 15:59 UTC, Zurqos commented
Map ziet er goed uit, de error die komt met het inladen heeft inderdaad niks met de map te maken

2022-11-29 16:12 UTC, closed without merging